on:
  push:
    paths:
      - "DC-*"
      - "adoc/*"

  pull_request:
    paths:
      - "DC-*"
      - "adoc/*"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: openSUSE/doc-ci@gha-validate
        with:
          dc-files: "DC-release-notes-all DC-release-notes-micro"
          validate-ids: true
          validate-images: true
          validate-tables: true
